### ISSUE TITLE
AspireWithPython deployment via DevOps

### ISSUE THREAD

**Issue by anemitoff** [dotnet/aspire-samples#777]
I get the following error when the Azure DevOps pipeline executes `azure-dev.yml` during `Provision Infrastructure`:
```
generating app host manifest: dotnet run --publisher manifest on project ...

Unhandled exception. Aspire.Hosting.DistributedApplicationException: The executable python could not be found in the virtual environment at '/home/vsts/work/1/s/pythonapp/.venv'
```

My `azure-dev.yml` looks like this:
```
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: 'Use Python 3.12'

  - script: |
      $(buildPython.pythonLocation)\python -m venv .venv
      source .venv/bin/activate
    displayName: setup virtual environment

  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)
```
There are no problems using `azd up`
